name: FoTClinicianMac
options:
  bundleIdPrefix: com.fot
  deploymentTarget:
    macOS: 14.0

packages:
  FoTPackages:
    path: ../../..

targets:
  FoTClinicianMac:
    type: application
    platform: macOS
    sources:
      - FoTClinicianMac
    resources:
      - FoTClinicianMac/Assets.xcassets
    dependencies:
      - package: FoTPackages
        product: FoTCore
      - package: FoTPackages
        product: FoTUI
      - package: FoTPackages
        product: FoTClinician
      - package: FoTPackages
        product: FoTAppIntents
    settings:
      base:
        INFOPLIST_FILE: FoTClinicianMac/Info.plist
        CODE_SIGN_ENTITLEMENTS: FoTClinicianMac/FoTClinicianMac.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.ClinicianMac
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LSApplicationCategoryType: "public.app-category.medical"
