name: PersonalHealthApp
options:
  bundleIdPrefix: com.fot
  deploymentTarget:
    iOS: 17.0

packages:
  FoTPackages:
    path: ../../..

targets:
  PersonalHealthApp:
    type: application
    platform: iOS
    sources:
      - PersonalHealth
    dependencies:
      - package: FoTPackages
        product: FoTCore
      - package: FoTPackages
        product: FoTUI
      - package: FoTPackages
        product: VQbitSubstrate
    settings:
      base:
        INFOPLIST_FILE: PersonalHealth/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.PersonalHealth
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        # Camera and health permissions
        INFOPLIST_KEY_NSCameraUsageDescription: "Capture health-related photos and symptoms"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Save health records"
        INFOPLIST_KEY_NSHealthShareUsageDescription: "Read health data from Apple Health"
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "Write health data to Apple Health"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Record location with health incidents"
        INFOPLIST_KEY_NSMotionUsageDescription: "Track activity and falls"

