name: FoTEducationApp
options:
  bundleIdPrefix: com.fot
  deploymentTarget:
    iOS: 17.0

packages:
  FoTPackages:
    path: ../../..

targets:
  FoTEducationApp:
    type: application
    platform: iOS
    sources:
      - FoTEducation
    dependencies:
      - package: FoTPackages
        product: FoTCore
      - package: FoTPackages
        product: FoTUI
      - package: FoTPackages
        product: FoTEducationK18
      - package: FoTPackages
        product: FoTAppIntents
      - package: FoTPackages
        product: VQbitSubstrate
    settings:
      base:
        INFOPLIST_FILE: FoTEducation/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.EducationApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: WWQQB728U5

