name: FoTParentApp
options:
  bundleIdPrefix: com.fot
  deploymentTarget:
    iOS: 17.0

packages:
  FoTPackages:
    path: ../../..

targets:
  FoTParentApp:
    type: application
    platform: iOS
    sources:
      - FoTParent
    resources:
      - FoTParent/Assets.xcassets
    dependencies:
      - package: FoTPackages
        product: FoTCore
      - package: FoTPackages
        product: FoTUI
      - package: FoTPackages
        product: FoTEducationK18
      - package: FoTPackages
        product: VQbitSubstrate
      - package: FoTPackages
        product: FoTAppIntents
    settings:
      base:
        INFOPLIST_FILE: FoTParent/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.ParentApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"

