name: FoTLegalApp
options:
  bundleIdPrefix: com.fot
  deploymentTarget:
    iOS: 17.0

packages:
  FoTPackages:
    path: ../../..

targets:
  FoTLegalApp:
    type: application
    platform: iOS
    sources:
      - FoTLegal
    resources:
      - FoTLegal/Assets.xcassets
    dependencies:
      - package: FoTPackages
        product: FoTCore
      - package: FoTPackages
        product: FoTUI
      - package: FoTPackages
        product: FoTLegalUS
      - package: FoTPackages
        product: FoTAppIntents
      - package: FoTPackages
        product: VQbitSubstrate
      - package: FoTPackages
        product: EthicsProvenance
    settings:
      base:
        INFOPLIST_FILE: FoTLegal/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.LegalApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: WWQQB728U5

