name: FoTClinicianApp
options:
  bundleIdPrefix: com.fot
  deploymentTarget:
    iOS: 17.0

packages:
  FoTPackages:
    path: ../../..

targets:
  FoTClinicianApp:
    type: application
    platform: iOS
    sources:
      - FoTClinician
    resources:
      - FoTClinician/Assets.xcassets
    dependencies:
      - package: FoTPackages
        product: FoTCore
      - package: FoTPackages
        product: FoTUI
      - package: FoTPackages
        product: FoTClinician
      - package: FoTPackages
        product: AKG
      - package: FoTPackages
        product: VQbitSubstrate
      - package: FoTPackages
        product: ReasonGraph
      - package: FoTPackages
        product: EthicsProvenance
      - package: FoTPackages
        product: PrivacyPHI
      - package: FoTPackages
        product: DataAdapters
      - package: FoTPackages
        product: FoTAppIntents
      - target: FoTClinicianWatchApp
    settings:
      base:
        INFOPLIST_FILE: FoTClinician/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.ClinicianApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
  
  FoTClinicianWatchApp:
    type: application
    platform: watchOS
    sources:
      - ../watchOS/FoTClinicianWatch
    resources:
      - ../watchOS/FoTClinicianWatch/Assets.xcassets
    dependencies:
      - package: FoTPackages
        product: FoTCore
      - package: FoTPackages
        product: FoTUI
      - package: FoTPackages
        product: FoTClinician
    settings:
      base:
        INFOPLIST_FILE: ../watchOS/FoTClinicianWatch/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.ClinicianApp.watchkitapp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
  
  FoTClinicianUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - FoTClinicianUITests
    dependencies:
      - target: FoTClinicianApp
    settings:
      base:
        TEST_TARGET_NAME: FoTClinicianApp
        PRODUCT_BUNDLE_IDENTIFIER: com.fot.ClinicianAppUITests

